services:
  - type: web
    name: flexishop-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: DATABASE_URL
        value: postgresql://flexishop_db_sftb_user:a860GeGaKMktvQVLA5mPVXjzD0OQu8U6@dpg-d32h9jadbo4c73aedbqg-a.oregon-postgres.render.com/flexishop_db_sftb
    autoDeploy: true 